# Generated by Django 4.0.4 on 2022-05-15 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
